apiVersion: v1
kind: Pod
metadata:
 name: workload
spec:
  containers:
    - name: iofileworkload
      image: nikolabo/alpineio
      volumeMounts:
        - name: host
          mountPath: /host
      env: 
      - name: user
        value: $user
      - name: access
        value: $access
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
  nodeSelector:
    kubernetes.io/hostname: aks-nodepool1-25096715-vmss000000
  hostIPC: true
  hostNetwork: true
  hostPID: true